FROM golang:1.26-alpine3.21 AS build

WORKDIR /app

# Modules layer
COPY go.mod go.sum ./
RUN go mod download

# Build layer
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -o /{{ .ServiceName }} ./cmd/app

FROM alpine:3.21 AS run

COPY --from=build /{{ .ServiceName }} /{{ .ServiceName }}
COPY --from=build /app/.env /.env

EXPOSE 8080

CMD ["/{{ .ServiceName }}"]
